from __future__ import annotations

import hashlib
import json
import logging
from datetime import datetime
from pathlib import Path
from uuid import uuid4

import fitz  # PyMuPDF

from .audit import utc_now
from .project import SurveyProject

logger = logging.getLogger(__name__)

PAGE_W, PAGE_H = 612, 792  # US Letter points
MARGIN = 54


def _sha256(path: Path) -> str:
    h=hashlib.sha256()
    with Path(path).open('rb') as f:
        for chunk in iter(lambda:f.read(1024*1024),b''):h.update(chunk)
    return h.hexdigest()


def _text(page, rect, text, *, size=10, bold=False, align=0, color=(0,0,0)):
    font='hebo' if bold else 'helv'
    page.insert_textbox(rect,str(text),fontsize=size,fontname=font,color=color,align=align,lineheight=1.2)


def _header(page, title: str, subtitle: str=''):
    _text(page,fitz.Rect(MARGIN,36,PAGE_W-MARGIN,62),'SurveySync',size=11,bold=True,color=(0.03,0.17,0.32))
    _text(page,fitz.Rect(MARGIN,62,PAGE_W-MARGIN,94),title,size=18,bold=True)
    if subtitle:_text(page,fitz.Rect(MARGIN,92,PAGE_W-MARGIN,118),subtitle,size=9,color=(0.35,0.38,0.42))
    page.draw_line(fitz.Point(MARGIN,120),fitz.Point(PAGE_W-MARGIN,120),color=(0.72,0.74,0.77),width=.7)


def _footer(page, page_no: int):
    page.draw_line(fitz.Point(MARGIN,PAGE_H-42),fitz.Point(PAGE_W-MARGIN,PAGE_H-42),color=(0.8,0.82,0.84),width=.5)
    _text(page,fitz.Rect(MARGIN,PAGE_H-37,PAGE_W-MARGIN,PAGE_H-20),f'Generated by SurveySync · Page {page_no}',size=8,color=(0.4,0.42,0.45),align=2)


def _section(page, y: float, heading: str, body: str) -> float:
    _text(page,fitz.Rect(MARGIN,y,PAGE_W-MARGIN,y+20),heading,size=11,bold=True,color=(0.03,0.17,0.32)); y+=22
    height=max(36, 13*(str(body).count('\n')+2))
    _text(page,fitz.Rect(MARGIN,y,PAGE_W-MARGIN,y+height),body,size=9);return y+height+12


def project_report(project: SurveyProject, output_path: Path, *, title: str='Survey Report', prepared_by: str='', project_number: str='', client: str='', scope: str='', methodology: str='', findings: str='', include_audit_summary: bool=True, signature_roles: list[str]|None=None) -> dict:
    output_path=Path(output_path);output_path.parent.mkdir(parents=True,exist_ok=True)
    doc=fitz.open();page=doc.new_page(width=PAGE_W,height=PAGE_H);_header(page,title,project.manifest.get('name','Survey Project'))
    y=138
    metadata=[('Project',project.manifest.get('name','')),('Project Number',project_number),('Client',client),('Prepared By',prepared_by),('Report Date',datetime.now().strftime('%Y-%m-%d')),('CRS',project.manifest.get('crs','')),('Horizontal Units',project.manifest.get('horizontal_units','')),('Vertical Units',project.manifest.get('vertical_units',''))]
    for label,value in metadata:
        _text(page,fitz.Rect(MARGIN,y,MARGIN+120,y+18),label,size=9,bold=True);_text(page,fitz.Rect(MARGIN+125,y,PAGE_W-MARGIN,y+18),value or '—',size=9);y+=18
    y+=10
    for heading,body in [('Scope',scope or 'No scope narrative entered.'),('Methodology',methodology or 'No methodology narrative entered.'),('Findings / QA Summary',findings or 'No findings narrative entered.')]:
        if y>650:_footer(page,len(doc));page=doc.new_page(width=PAGE_W,height=PAGE_H);_header(page,title);y=138
        y=_section(page,y,heading,body)
    _footer(page,len(doc))

    # Project metrics / audit summary page.
    page=doc.new_page(width=PAGE_W,height=PAGE_H);_header(page,'Project Data & Traceability',project.manifest.get('name',''));y=138
    summary=project.summary().get('counts',{})
    for k,v in summary.items():
        _text(page,fitz.Rect(MARGIN,y,MARGIN+220,y+18),k.replace('_',' ').title(),size=9,bold=True);_text(page,fitz.Rect(MARGIN+230,y,PAGE_W-MARGIN,y+18),str(v),size=9);y+=18
    if include_audit_summary:
        y+=12;_text(page,fitz.Rect(MARGIN,y,PAGE_W-MARGIN,y+20),'Recent Audit Events',size=11,bold=True);y+=24
        for event in project.db.recent_audit(18):
            line=f"{event['ts_utc']}  |  {event['module']}  |  {event['action']}"
            _text(page,fitz.Rect(MARGIN,y,PAGE_W-MARGIN,y+14),line,size=7.5);y+=14
    _footer(page,len(doc))

    # Signature / seal page.
    roles=signature_roles or ['Professional Land Surveyor (PLS)','Professional Engineer (PE)']
    page=doc.new_page(width=PAGE_W,height=PAGE_H);_header(page,'Certification / Signature & Seal',project.manifest.get('name',''));y=150
    _text(page,fitz.Rect(MARGIN,y,PAGE_W-MARGIN,y+58),'This page is intentionally reserved for professional review, certification, signature, and seal. SurveySync does not apply or simulate a professional seal.',size=10);y+=82
    for role in roles:
        box=fitz.Rect(MARGIN,y,PAGE_W-MARGIN,y+155);page.draw_rect(box,color=(0.55,0.58,0.62),width=.8)
        _text(page,fitz.Rect(MARGIN+12,y+12,PAGE_W-MARGIN-12,y+32),role,size=10,bold=True)
        _text(page,fitz.Rect(MARGIN+12,y+48,MARGIN+300,y+68),'Name: ______________________________________',size=9)
        _text(page,fitz.Rect(MARGIN+12,y+76,MARGIN+300,y+96),'License No.: _________________________________',size=9)
        _text(page,fitz.Rect(MARGIN+12,y+104,MARGIN+300,y+124),'Signature / Date: _____________________________',size=9)
        _text(page,fitz.Rect(PAGE_W-210,y+45,PAGE_W-MARGIN-12,y+125),'SEAL AREA',size=9,bold=True,align=1,color=(0.45,0.48,0.52))
        y+=175
    _footer(page,len(doc))
    doc.set_metadata({'title':title,'author':prepared_by or 'SurveySync','subject':project.manifest.get('name',''),'creator':'SurveySync'})
    doc.save(output_path,garbage=4,deflate=True);doc.close()
    return register_deliverable(project,output_path,module='ReportSync',kind='survey_report_pdf',metadata={'title':title,'prepared_by':prepared_by,'project_number':project_number,'client':client})


def register_deliverable(project: SurveyProject, path: Path, *, module: str, kind: str, metadata: dict|None=None, status: str='FINAL') -> dict:
    path=Path(path).resolve();digest=_sha256(path);did=uuid4().hex
    with project.db.connect() as conn:
        conn.execute('INSERT INTO deliverables(deliverable_id,ts_utc,module,kind,filename,path,sha256,status,metadata_json) VALUES(?,?,?,?,?,?,?,?,?)',(did,utc_now(),module,kind,path.name,str(path),digest,status,json.dumps(metadata or {},sort_keys=True)))
    project.db.audit(module,'DELIVERABLE_CREATED',object_type='deliverable',object_id=did,details={'kind':kind,'filename':path.name,'sha256':digest,'status':status})
    result={'deliverable_id':did,'path':str(path),'filename':path.name,'sha256':digest,'kind':kind,'status':status,'metadata':metadata or {}}
    if status == 'FINAL':
        try:
            from .notifications import maybe_notify_deliverable
            result['notification']=maybe_notify_deliverable(project,result)
        except Exception as exc:
            result['notification']={'status':'FAILED','reason':str(exc)}
    return result


def list_deliverables(project: SurveyProject, limit: int=100) -> list[dict]:
    with project.db.connect() as conn:rows=conn.execute('SELECT * FROM deliverables ORDER BY ts_utc DESC LIMIT ?',(max(1,min(limit,1000)),)).fetchall()
    out=[]
    for row in rows:
        d=dict(row);d['metadata']=json.loads(d.pop('metadata_json') or '{}');out.append(d)
    return out


def control_report(project: SurveyProject, output_path: Path, *, title: str='Project Control Report', prepared_by: str='') -> dict:
    """Create a traceable control/level/traverse summary PDF.

    This report intentionally reports the deterministic results already stored in
    the project database; it does not recompute or silently adjust survey work.
    """
    output_path=Path(output_path);output_path.parent.mkdir(parents=True,exist_ok=True)
    with project.db.connect() as conn:
        # Reports use the explicitly active revision when one has been selected.
        # Older projects have no selection row, so latest-revision behavior is
        # preserved automatically for backward compatibility.
        controls=[dict(r) for r in conn.execute("""
            SELECT c.* FROM control_solutions c
            WHERE c.solution_id = COALESCE(
                (SELECT ss.solution_id FROM solution_selections ss WHERE ss.solution_kind='control' AND ss.object_id=c.control_id),
                (SELECT x.solution_id FROM control_solutions x WHERE x.control_id=c.control_id ORDER BY x.revision DESC LIMIT 1)
            )
            ORDER BY c.control_id
        """).fetchall()]
        levels=[dict(r) for r in conn.execute("""
            SELECT r.run_id,r.name,r.status,r.start_point,r.end_point,s.revision,s.closure,s.adjusted,s.method,s.qc_json
            FROM level_runs r
            LEFT JOIN level_solutions s ON s.solution_id=COALESCE(
                (SELECT ss.solution_id FROM solution_selections ss WHERE ss.solution_kind='level' AND ss.object_id=r.run_id),
                (SELECT x.solution_id FROM level_solutions x WHERE x.run_id=r.run_id ORDER BY x.revision DESC LIMIT 1)
            )
            ORDER BY r.created_utc
        """).fetchall()]
        traverses=[dict(r) for r in conn.execute("SELECT r.run_id,r.name,r.status,s.revision,s.linear_closure,s.precision_ratio,s.adjusted,s.method FROM traverse_runs r LEFT JOIN traverse_solutions s ON s.solution_id=(SELECT solution_id FROM traverse_solutions x WHERE x.run_id=r.run_id ORDER BY revision DESC LIMIT 1) ORDER BY r.created_utc").fetchall()]
    doc=fitz.open();page=doc.new_page(width=PAGE_W,height=PAGE_H);_header(page,title,project.manifest.get('name',''));y=140
    for label,value in [('Prepared By',prepared_by),('CRS',project.manifest.get('crs','')),('Horizontal Units',project.manifest.get('horizontal_units','')),('Vertical Units',project.manifest.get('vertical_units','')),('Generated',datetime.now().strftime('%Y-%m-%d %H:%M'))]:
        _text(page,fitz.Rect(MARGIN,y,MARGIN+130,y+17),label,size=9,bold=True);_text(page,fitz.Rect(MARGIN+135,y,PAGE_W-MARGIN,y+17),value or '—',size=9);y+=18
    y+=16
    _text(page,fitz.Rect(MARGIN,y,PAGE_W-MARGIN,y+22),'Final Control Solutions',size=11,bold=True);y+=24
    if not controls:_text(page,fitz.Rect(MARGIN,y,PAGE_W-MARGIN,y+28),'No control solutions are stored.',size=9);y+=30
    else:
        for c in controls:
            text=f"{c['control_id']}  Active Rev {c['revision']}  {c['method']}  N {c['northing']:.4f}  E {c['easting']:.4f}"
            if c.get('elevation') is not None:text+=f"  Z {c['elevation']:.4f}"
            text+=f"  {'PASS' if c.get('pass') else 'REVIEW'}"
            _text(page,fitz.Rect(MARGIN,y,PAGE_W-MARGIN,y+15),text,size=8.3);y+=16
            if y>720:_footer(page,len(doc));page=doc.new_page(width=PAGE_W,height=PAGE_H);_header(page,title);y=140
    _footer(page,len(doc))

    page=doc.new_page(width=PAGE_W,height=PAGE_H);_header(page,'Leveling & Traverse QC',project.manifest.get('name',''));y=140
    _text(page,fitz.Rect(MARGIN,y,PAGE_W-MARGIN,y+22),'Level Runs',size=11,bold=True);y+=24
    for l in levels:
        qc={}
        try:qc=json.loads(l.get('qc_json') or '{}')
        except Exception:
            logger.warning("Stored level QC JSON could not be decoded for run %s.", l.get('run_id') or l.get('name'), exc_info=True)
        line=f"{l['name']}  |  {l.get('status') or ''}  |  Rev {l.get('revision') or '—'}  |  Closure {l.get('closure') if l.get('closure') is not None else '—'}  |  {l.get('method') or '—'}"
        _text(page,fitz.Rect(MARGIN,y,PAGE_W-MARGIN,y+16),line,size=8.5);y+=17
        if qc.get('qc_flags'):_text(page,fitz.Rect(MARGIN+12,y,PAGE_W-MARGIN,y+28),'QC: '+' | '.join(qc['qc_flags'][:3]),size=7.5,color=(0.65,0.25,0.1));y+=30
    if not levels:_text(page,fitz.Rect(MARGIN,y,PAGE_W-MARGIN,y+20),'No level runs stored.',size=9);y+=24
    y+=12;_text(page,fitz.Rect(MARGIN,y,PAGE_W-MARGIN,y+22),'Traverse Runs',size=11,bold=True);y+=24
    for t in traverses:
        prec=t.get('precision_ratio');prec_txt=f"1:{prec:.0f}" if isinstance(prec,(int,float)) and prec else '—'
        line=f"{t['name']}  |  {t.get('status') or ''}  |  Rev {t.get('revision') or '—'}  |  Closure {t.get('linear_closure') if t.get('linear_closure') is not None else '—'}  |  Precision {prec_txt}  |  {t.get('method') or '—'}"
        _text(page,fitz.Rect(MARGIN,y,PAGE_W-MARGIN,y+16),line,size=8.5);y+=18
    if not traverses:_text(page,fitz.Rect(MARGIN,y,PAGE_W-MARGIN,y+20),'No traverse runs stored.',size=9)
    _footer(page,len(doc))

    page=doc.new_page(width=PAGE_W,height=PAGE_H);_header(page,'Professional Review / Signature & Seal',project.manifest.get('name',''));y=160
    _text(page,fitz.Rect(MARGIN,y,PAGE_W-MARGIN,y+60),'The control solutions, leveling adjustments, and traverse adjustments shown in this report remain subject to professional review and approval. SurveySync does not apply or simulate a professional seal.',size=10);y+=90
    for role in ('Professional Land Surveyor (PLS)','Professional Engineer (PE)'):
        page.draw_rect(fitz.Rect(MARGIN,y,PAGE_W-MARGIN,y+145),color=(0.6,0.6,0.6),width=.7);_text(page,fitz.Rect(MARGIN+12,y+12,PAGE_W-MARGIN-12,y+32),role,size=10,bold=True);_text(page,fitz.Rect(MARGIN+12,y+55,MARGIN+330,y+75),'Signature / Date: _________________________________',size=9);_text(page,fitz.Rect(PAGE_W-210,y+45,PAGE_W-MARGIN-10,y+110),'SEAL AREA',size=9,bold=True,align=1,color=(0.45,0.45,0.45));y+=165
    _footer(page,len(doc));doc.set_metadata({'title':title,'author':prepared_by or 'SurveySync','creator':'SurveySync'});doc.save(output_path,garbage=4,deflate=True);doc.close()
    return register_deliverable(project,output_path,module='ControlSync',kind='control_report_pdf',metadata={'title':title,'prepared_by':prepared_by,'control_count':len(controls),'level_run_count':len(levels),'traverse_run_count':len(traverses)})
