from __future__ import annotations

import csv
import io
import json
import sqlite3
import struct
import tempfile
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

from .models import AppState, ResultRecord
from surveysync import __version__ as SURVEYSYNC_VERSION
from . import __version__ as FIELDBOOK_ENGINE_VERSION

EXPORT_PROVENANCE = f"Generated by SurveySync v{SURVEYSYNC_VERSION} (FieldBookSync engine v{FIELDBOOK_ENGINE_VERSION})"


def _fmt(value):
    return "" if value is None else value


def _structures_csv(results: Iterable[ResultRecord]) -> str:
    out = io.StringIO(newline="")
    writer = csv.writer(out)
    writer.writerow([
        "PointID", "Northing", "Easting", "Elevation", "Code", "Category",
        "Status", "DipDetailStatus", "QAReview", "ModelConfidence", "SmartConfidence", "ReviewState",
        "PipeCount", "QCFlags", "Notes"
    ])
    for r in results:
        writer.writerow([
            r.point_id, _fmt(r.northing), _fmt(r.easting), _fmt(r.elevation), r.code, r.category,
            r.status.value, r.dip_status.value, "YES" if r.qa_needs_review else "NO", round(r.confidence, 4), round(r.smart_confidence, 1), r.review_state.value,
            len(r.pipes), " | ".join(r.qc_flags), r.notes,
        ])
    return out.getvalue()


def _pipes_csv(results: Iterable[ResultRecord]) -> str:
    out = io.StringIO(newline="")
    writer = csv.writer(out)
    writer.writerow([
        "PointID", "PipeIndex", "Dip", "DipRaw", "InvertElevation", "DiameterIn", "DiameterRaw",
        "Material", "AzimuthDeg", "AzimuthRaw", "ConnectedPointID", "ConnectionScore", "QCFlags", "Notes"
    ])
    for r in results:
        for i, p in enumerate(r.pipes, start=1):
            writer.writerow([
                r.point_id, i, _fmt(p.dip), p.dip_raw or "", _fmt(p.invert_elevation), _fmt(p.diameter_in), p.diameter_raw or "",
                p.material or "", _fmt(p.azimuth_deg), p.azimuth_raw or "", p.connected_point_id or "",
                _fmt(p.connection_score), " | ".join(p.qc_flags), p.notes or "",
            ])
    return out.getvalue()


def _network_csv(state: AppState) -> str:
    out = io.StringIO(newline="")
    writer = csv.writer(out)
    writer.writerow(["FromPoint", "ToPoint", "FromPipeIndex", "ToPipeIndex", "Distance", "BearingErrorDeg", "ReciprocalErrorDeg", "Score", "Status", "Notes"])
    for e in state.network_edges:
        writer.writerow([e.from_point, e.to_point, e.from_pipe_index, _fmt(e.to_pipe_index), _fmt(e.distance), _fmt(e.bearing_error_deg), _fmt(e.reciprocal_error_deg), e.score, e.status, e.notes])
    return out.getvalue()


def _review_csv(state: AppState) -> str:
    out = io.StringIO(newline="")
    writer = csv.writer(out)
    writer.writerow(["Type", "PointID_or_Raw", "Status", "SmartConfidence", "Source", "Page", "Reason"])
    for r in state.results:
        if r.qa_needs_review or r.qc_flags:
            source = r.evidence_records[0].source_name if r.evidence_records else ""
            page = r.evidence_records[0].page_number if r.evidence_records else ""
            reason = " | ".join([x for x in [r.notes, *r.qc_flags] if x])
            writer.writerow(["Matched", r.point_id, "REVIEW" if r.qa_needs_review else r.status.value, round(r.smart_confidence, 1), source, page, reason])
    for u in state.unmatched:
        writer.writerow(["Unmatched", u.point_id_raw or "", "REVIEW", round(u.confidence * 100, 1), u.source_name, u.page_number, u.reason])
    return out.getvalue()


def _arcgis_csv(results: Iterable[ResultRecord]) -> str:
    out = io.StringIO(newline="")
    writer = csv.writer(out)
    writer.writerow(["PointID", "X_Easting", "Y_Northing", "Elevation", "Code", "Category", "Status", "DipDetailStatus", "QAReview", "SmartConf", "PipeCount", "QCFlagCount"])
    for r in results:
        writer.writerow([r.point_id, _fmt(r.easting), _fmt(r.northing), _fmt(r.elevation), r.code, r.category, r.status.value, r.dip_status.value, "YES" if r.qa_needs_review else "NO", round(r.smart_confidence, 1), len(r.pipes), len(r.qc_flags)])
    return out.getvalue()


def _geojson(state: AppState) -> str:
    features = []
    for r in state.results:
        if r.easting is None or r.northing is None:
            continue
        features.append({
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [r.easting, r.northing]},
            "properties": {
                "PointID": r.point_id, "Code": r.code, "Category": r.category,
                "Status": r.status.value, "DipDetailStatus": r.dip_status.value, "QAReview": r.qa_needs_review, "SmartConfidence": r.smart_confidence,
                "PipeCount": len(r.pipes), "QCFlags": " | ".join(r.qc_flags),
            },
        })
    by_id = {r.point_id: r for r in state.results}
    for e in state.network_edges:
        a, b = by_id.get(e.from_point), by_id.get(e.to_point)
        if not a or not b or None in (a.easting, a.northing, b.easting, b.northing):
            continue
        features.append({
            "type": "Feature",
            "geometry": {"type": "LineString", "coordinates": [[a.easting, a.northing], [b.easting, b.northing]]},
            "properties": {"FromPoint": e.from_point, "ToPoint": e.to_point, "Score": e.score, "Status": e.status},
        })
    return json.dumps({"type": "FeatureCollection", "name": "FieldBookSync", "features": features}, indent=2)


def _kml(state: AppState) -> str:
    esc = lambda s: str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    placemarks = []
    # KML requires geographic lon/lat. Survey coordinates are frequently projected, so
    # they are represented as ExtendedData only until the correct CRS is assigned in GIS.
    for r in state.results:
        placemarks.append(
            f"<Placemark><name>{esc(r.point_id)}</name><description>{esc(r.code)} · {esc(r.status.value)}</description>"
            f"<ExtendedData><Data name=\"Easting\"><value>{esc(_fmt(r.easting))}</value></Data>"
            f"<Data name=\"Northing\"><value>{esc(_fmt(r.northing))}</value></Data>"
            f"<Data name=\"SmartConfidence\"><value>{r.smart_confidence:.1f}</value></Data></ExtendedData></Placemark>"
        )
    return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><kml xmlns=\"http://www.opengis.net/kml/2.2\"><Document>" + "".join(placemarks) + "</Document></kml>"


def _dxf(state: AppState) -> str:
    """Write a simple ASCII DXF using raw survey XY coordinates.

    DXF is Cartesian, so unlike KML it can safely carry projected survey coordinates without
    pretending to know the CRS. Layer names preserve QA status and inferred-network status.
    """
    out: list[str] = ["0", "SECTION", "2", "HEADER", "0", "ENDSEC", "0", "SECTION", "2", "ENTITIES"]
    by_id = {r.point_id: r for r in state.results}

    def add(code: int | str, value) -> None:
        out.extend([str(code), str(value)])

    for r in state.results:
        if r.easting is None or r.northing is None:
            continue
        layer = f"STRUCT_{r.status.value}"[:31]
        add(0, "POINT"); add(8, layer); add(10, float(r.easting)); add(20, float(r.northing)); add(30, float(r.elevation or 0.0))
        # Point labels are separate TEXT entities so CAD reviewers can identify structures quickly.
        add(0, "TEXT"); add(8, "POINT_LABELS"); add(10, float(r.easting)); add(20, float(r.northing)); add(30, float(r.elevation or 0.0)); add(40, 2.5); add(1, r.point_id)

    for edge in state.network_edges:
        a, b = by_id.get(edge.from_point), by_id.get(edge.to_point)
        if not a or not b or None in (a.easting, a.northing, b.easting, b.northing):
            continue
        add(0, "LINE"); add(8, f"NET_{edge.status}"[:31])
        add(10, float(a.easting)); add(20, float(a.northing)); add(30, float(a.elevation or 0.0))
        add(11, float(b.easting)); add(21, float(b.northing)); add(31, float(b.elevation or 0.0))

    out.extend(["0", "ENDSEC", "0", "EOF"])
    return "\n".join(out) + "\n"


def _gpkg_geom_point(x: float, y: float, srs_id: int = -1) -> bytes:
    # GeoPackage binary header: GP, version 0, little-endian/no-envelope flags, srs id.
    return b"GP" + bytes([0, 1]) + struct.pack("<i", srs_id) + struct.pack("<BI2d", 1, 1, float(x), float(y))


def _gpkg_geom_line(coords: list[tuple[float, float]], srs_id: int = -1) -> bytes:
    header = b"GP" + bytes([0, 1]) + struct.pack("<i", srs_id)
    wkb = struct.pack("<BII", 1, 2, len(coords))
    for x, y in coords:
        wkb += struct.pack("<2d", float(x), float(y))
    return header + wkb


def _write_geopackage(state: AppState, path: Path) -> Path:
    """Create a GeoPackage using Undefined Cartesian (SRS -1), never a guessed CRS."""
    path.unlink(missing_ok=True)
    con = sqlite3.connect(path)
    try:
        con.execute("PRAGMA application_id=1196444487")  # ASCII GPKG
        con.execute("PRAGMA user_version=10300")
        con.executescript("""
        CREATE TABLE gpkg_spatial_ref_sys (
          srs_name TEXT NOT NULL, srs_id INTEGER NOT NULL PRIMARY KEY, organization TEXT NOT NULL,
          organization_coordsys_id INTEGER NOT NULL, definition TEXT NOT NULL, description TEXT
        );
        CREATE TABLE gpkg_contents (
          table_name TEXT NOT NULL PRIMARY KEY, data_type TEXT NOT NULL, identifier TEXT UNIQUE,
          description TEXT DEFAULT '', last_change DATETIME NOT NULL,
          min_x DOUBLE, min_y DOUBLE, max_x DOUBLE, max_y DOUBLE, srs_id INTEGER
        );
        CREATE TABLE gpkg_geometry_columns (
          table_name TEXT NOT NULL, column_name TEXT NOT NULL, geometry_type_name TEXT NOT NULL,
          srs_id INTEGER NOT NULL, z TINYINT NOT NULL, m TINYINT NOT NULL,
          PRIMARY KEY (table_name, column_name)
        );
        CREATE TABLE structures (
          fid INTEGER PRIMARY KEY AUTOINCREMENT, geom BLOB, PointID TEXT, Code TEXT, Category TEXT,
          Elevation REAL, Dipped TEXT, SmartConf REAL, PipeCount INTEGER, QCFlags TEXT
        );
        CREATE TABLE network_connections (
          fid INTEGER PRIMARY KEY AUTOINCREMENT, geom BLOB, FromPoint TEXT, ToPoint TEXT,
          Score REAL, Status TEXT, Distance REAL, BearingErr REAL, ReciprocalErr REAL
        );
        CREATE TABLE pipes (
          fid INTEGER PRIMARY KEY AUTOINCREMENT, PointID TEXT, PipeIndex INTEGER, Dip REAL,
          InvertElev REAL, DiameterIn REAL, Material TEXT, AzimuthDeg REAL, ConnectedPt TEXT,
          ConnectScore REAL, QCFlags TEXT
        );
        """)
        con.execute("INSERT INTO gpkg_spatial_ref_sys VALUES (?,?,?,?,?,?)", (
            "Undefined Cartesian", -1, "NONE", -1, "undefined",
            "Survey XY imported without guessing a coordinate reference system."
        ))
        con.execute("INSERT INTO gpkg_spatial_ref_sys VALUES (?,?,?,?,?,?)", (
            "Undefined Geographic", 0, "NONE", 0, "undefined", "undefined geographic coordinate reference system"
        ))
        coords = [(float(r.easting), float(r.northing)) for r in state.results if r.easting is not None and r.northing is not None]
        bounds = (
            min((x for x, _ in coords), default=None), min((y for _, y in coords), default=None),
            max((x for x, _ in coords), default=None), max((y for _, y in coords), default=None),
        )
        now = datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z")
        for table, dtype, ident, srs in [
            ("structures", "features", "FieldBook Sync Structures", -1),
            ("network_connections", "features", "Inferred Network Connections", -1),
            ("pipes", "attributes", "FieldBook Sync Pipes", None),
        ]:
            b = bounds if table != "pipes" else (None, None, None, None)
            con.execute(
                "INSERT INTO gpkg_contents(table_name,data_type,identifier,description,last_change,min_x,min_y,max_x,max_y,srs_id) VALUES (?,?,?,?,?,?,?,?,?,?)",
                (table, dtype, ident, EXPORT_PROVENANCE, now, *b, srs),
            )
        con.execute("INSERT INTO gpkg_geometry_columns VALUES (?,?,?,?,?,?)", ("structures", "geom", "POINT", -1, 0, 0))
        con.execute("INSERT INTO gpkg_geometry_columns VALUES (?,?,?,?,?,?)", ("network_connections", "geom", "LINESTRING", -1, 0, 0))

        by_id = {r.point_id: r for r in state.results}
        for r in state.results:
            if r.easting is not None and r.northing is not None:
                con.execute(
                    "INSERT INTO structures(geom,PointID,Code,Category,Elevation,Dipped,SmartConf,PipeCount,QCFlags) VALUES (?,?,?,?,?,?,?,?,?)",
                    (_gpkg_geom_point(r.easting, r.northing), r.point_id, r.code, r.category, r.elevation,
                     r.status.value, r.smart_confidence, len(r.pipes), " | ".join(r.qc_flags)),
                )
            for i, pipe in enumerate(r.pipes, start=1):
                con.execute(
                    "INSERT INTO pipes(PointID,PipeIndex,Dip,InvertElev,DiameterIn,Material,AzimuthDeg,ConnectedPt,ConnectScore,QCFlags) VALUES (?,?,?,?,?,?,?,?,?,?)",
                    (r.point_id, i, pipe.dip, pipe.invert_elevation, pipe.diameter_in, pipe.material,
                     pipe.azimuth_deg, pipe.connected_point_id, pipe.connection_score, " | ".join(pipe.qc_flags)),
                )
        for edge in state.network_edges:
            a, b = by_id.get(edge.from_point), by_id.get(edge.to_point)
            if not a or not b or None in (a.easting, a.northing, b.easting, b.northing):
                continue
            con.execute(
                "INSERT INTO network_connections(geom,FromPoint,ToPoint,Score,Status,Distance,BearingErr,ReciprocalErr) VALUES (?,?,?,?,?,?,?,?)",
                (_gpkg_geom_line([(a.easting, a.northing), (b.easting, b.northing)]), edge.from_point,
                 edge.to_point, edge.score, edge.status, edge.distance, edge.bearing_error_deg, edge.reciprocal_error_deg),
            )
        con.commit()
    finally:
        con.close()
    return path


def _write_shapefiles(state: AppState, folder: Path) -> list[Path]:
    """Write structures/network Shapefiles without a .prj because CRS is unknown."""
    import shapefile  # pyshp

    folder.mkdir(parents=True, exist_ok=True)
    structures = folder / "structures"
    w = shapefile.Writer(str(structures), shapeType=shapefile.POINT)
    w.autoBalance = 1
    w.field("PointID", "C", size=40)
    w.field("Code", "C", size=40)
    w.field("Category", "C", size=40)
    w.field("Elevation", "F", decimal=4)
    w.field("Dipped", "C", size=12)
    w.field("SmartConf", "F", decimal=1)
    w.field("PipeCount", "N", decimal=0)
    for r in state.results:
        if r.easting is None or r.northing is None:
            continue
        w.point(float(r.easting), float(r.northing))
        w.record(r.point_id, r.code[:40], r.category[:40], r.elevation, r.status.value, r.smart_confidence, len(r.pipes))
    w.close()
    (folder / "structures.cpg").write_text("UTF-8", encoding="ascii")

    lines = folder / "network_connections"
    w = shapefile.Writer(str(lines), shapeType=shapefile.POLYLINE)
    w.autoBalance = 1
    w.field("FromPoint", "C", size=40)
    w.field("ToPoint", "C", size=40)
    w.field("Score", "F", decimal=1)
    w.field("Status", "C", size=16)
    w.field("Distance", "F", decimal=3)
    by_id = {r.point_id: r for r in state.results}
    for edge in state.network_edges:
        a, b = by_id.get(edge.from_point), by_id.get(edge.to_point)
        if not a or not b or None in (a.easting, a.northing, b.easting, b.northing):
            continue
        w.line([[[float(a.easting), float(a.northing)], [float(b.easting), float(b.northing)]]])
        w.record(edge.from_point, edge.to_point, edge.score, edge.status, edge.distance)
    w.close()
    (folder / "network_connections.cpg").write_text("UTF-8", encoding="ascii")
    return sorted(folder.glob("*"))


def export_shapefiles_to_folder(state: AppState, folder: Path, *, include_network: bool = True) -> dict[str, str | None]:
    """Export native Shapefile sidecars directly to a user-selected folder.

    Files are first built in a staging directory and then replaced in the destination so a
    failed writer does not leave a half-written .shp/.dbf/.shx set. Coordinate system is
    intentionally left undefined here; the ArcGIS integration can optionally define it from
    the selected target map after an explicit user opt-in.
    """
    folder = Path(folder)
    folder.mkdir(parents=True, exist_ok=True)
    if not any(r.easting is not None and r.northing is not None for r in state.results):
        raise ValueError("There are no result coordinates available for Shapefile export.")
    with tempfile.TemporaryDirectory(prefix="fbs_shp_stage_", dir=str(folder)) as td:
        staged = Path(td)
        _write_shapefiles(state, staged)
        prefixes = {"structures"}
        if include_network:
            prefixes.add("network_connections")
        for source in staged.iterdir():
            if source.stem not in prefixes:
                continue
            target = folder / source.name
            target.unlink(missing_ok=True)
            source.replace(target)
    structures = folder / "structures.shp"
    network = folder / "network_connections.shp"
    return {
        "structures": str(structures),
        "network": str(network) if include_network and network.exists() else None,
    }


def _arcgis_helper_py() -> str:
    # Uses classic ArcPy function names that are available in both ArcGIS Desktop 10.x
    # and ArcGIS Pro. No spatial reference is guessed; users can define one in ArcGIS.
    return r'''# Run this script from ArcGIS Pro Python or ArcGIS Desktop / ArcMap 10.x Python.
import arcpy, os
folder = os.path.dirname(os.path.abspath(__file__))
out_gdb = os.path.join(folder, "FieldBookSync.gdb")
if not arcpy.Exists(out_gdb):
    arcpy.CreateFileGDB_management(folder, "FieldBookSync.gdb")
xy = os.path.join(folder, "arcgis_xy_import.csv")
structures = os.path.join(out_gdb, "Structures")
print("Creating structures. IMPORTANT: assign the correct survey coordinate system in ArcGIS before production use.")
if arcpy.Exists(structures):
    arcpy.Delete_management(structures)
layer_name = "FieldBookSync_XY_Event"
arcpy.MakeXYEventLayer_management(xy, "X_Easting", "Y_Northing", layer_name)
arcpy.CopyFeatures_management(layer_name, structures)
for source_name, out_name in [("pipes.csv", "Pipes"), ("network_connections.csv", "NetworkConnections")]:
    src = os.path.join(folder, source_name)
    dst = os.path.join(out_gdb, out_name)
    if arcpy.Exists(dst):
        arcpy.Delete_management(dst)
    arcpy.TableToTable_conversion(src, out_gdb, out_name)
print(out_gdb)
'''


def create_export_zip(state: AppState, export_dir: Path) -> Path:
    export_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = export_dir / f"FieldBookSync_Export_{stamp}.zip"
    audit = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "project_name": state.project_name,
        "selected_profile": state.selected_profile,
        "survey_issue_count": len(state.survey_issues),
        "unmatched_count": len(state.unmatched),
        "results": [r.model_dump(mode="json") for r in state.results],
        "network_edges": [e.model_dump(mode="json") for e in state.network_edges],
        "ocr_candidates": [c.model_dump(mode="json") for c in state.ocr_candidates],
        "history": [h.model_dump(mode="json") for h in state.history],
        "survey_issues": [i.model_dump(mode="json") for i in state.survey_issues],
        "unmatched": [u.model_dump(mode="json") for u in state.unmatched],
    }
    kml = _kml(state)
    with tempfile.TemporaryDirectory(prefix="fbs_gis_") as td:
        gis_dir = Path(td)
        gpkg_path = _write_geopackage(state, gis_dir / "fieldbook_sync.gpkg")
        shp_files = _write_shapefiles(state, gis_dir / "shapefile")
        with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            zf.write(gpkg_path, "fieldbook_sync.gpkg")
            for shp in shp_files:
                zf.write(shp, f"shapefile/{shp.name}")
            zf.writestr("structures.csv", _structures_csv(state.results).encode("utf-8-sig"))
            zf.writestr("pipes.csv", _pipes_csv(state.results).encode("utf-8-sig"))
            zf.writestr("network_connections.csv", _network_csv(state).encode("utf-8-sig"))
            zf.writestr("review_queue.csv", _review_csv(state).encode("utf-8-sig"))
            zf.writestr("arcgis_xy_import.csv", _arcgis_csv(state.results).encode("utf-8-sig"))
            zf.writestr("fieldbook_sync.geojson", _geojson(state).encode("utf-8"))
            zf.writestr("fieldbook_sync.dxf", _dxf(state).encode("utf-8"))
            zf.writestr("fieldbook_sync.kml", kml.encode("utf-8"))
            kmz_mem = io.BytesIO()
            with zipfile.ZipFile(kmz_mem, "w", compression=zipfile.ZIP_DEFLATED) as kmz:
                kmz.writestr("doc.kml", kml.encode("utf-8"))
            zf.writestr("fieldbook_sync.kmz", kmz_mem.getvalue())
            zf.writestr("create_arcgis_file_gdb.py", _arcgis_helper_py().encode("utf-8"))
            zf.writestr("audit.json", json.dumps(audit, indent=2, ensure_ascii=False).encode("utf-8"))
            zf.writestr(
                "README.txt",
                (
                    f"SurveySync v{SURVEYSYNC_VERSION} export (FieldBookSync engine v{FIELDBOOK_ENGINE_VERSION})\n\n"
                    "arcgis_xy_import.csv is designed for ArcGIS Pro or ArcGIS Desktop / ArcMap 10.x.\n"
                    "X field: X_Easting; Y field: Y_Northing.\n"
                    "IMPORTANT: choose the correct coordinate system. FieldBook Sync does not guess it.\n"
                    "fieldbook_sync.gpkg contains Structures, Pipes, and Network Connections using Undefined Cartesian (SRS -1). Assign the real CRS in GIS.\n"
                    "shapefile/ contains Structures and Network Connections with no .prj because the CRS is intentionally unknown.\n"
                    "fieldbook_sync.geojson uses raw survey XY coordinates and intentionally has no claimed CRS.\n"
                    "fieldbook_sync.dxf contains Cartesian survey points, PointID labels, and inferred network lines in raw survey XY.\n"
                    "KML/KMZ stores projected XY as attributes only because KML requires geographic coordinates.\n"
                    "create_arcgis_file_gdb.py can be run from either the ArcGIS Pro or ArcGIS Desktop / ArcMap 10.x Python environment to create a File GDB.\n"
                ).encode("utf-8"),
            )
    return path


def direct_export_text(state: AppState, fmt: str) -> tuple[str, str, str]:
    """Return (filename, media_type, text) for direct lightweight GIS exports."""
    fmt = (fmt or "").lower().lstrip(".")
    if fmt == "geojson":
        return "fieldbook_sync.geojson", "application/geo+json", _geojson(state)
    if fmt == "kml":
        return "fieldbook_sync.kml", "application/vnd.google-earth.kml+xml", _kml(state)
    if fmt == "dxf":
        return "fieldbook_sync.dxf", "application/dxf", _dxf(state)
    raise ValueError(f"Unsupported direct export format: {fmt}")
